export const defaults = {
    year: 2025,
    inputs: {
      'Land Cost($)':      50000,
      'Building Cost ($)':      12000000,
      'Installation Cost ($)':   3000000,
      'Equipment Cost ($)':      8000000,
      'Commissioning Fees ($)':   500000,
      'Licensing Fees ($)':       250000,
    },
    deprInputs: {
      'Land Value': 0,
      'Land Life': 0,
      'GMP Facility Shell (3000 sqm) Value': 0,
      'GMP Facility Shell (3000 sqm) Life': 0,
      'Equipment & Installation Value': 0,
      'Equipment & Installation Life': 0,
      'Office Equipment Value': 0,
      'Office Equipment Life': 0,
      'Accounting & Other Software Value': 0,
      'Accounting & Other Software Life': 0,
      'Vehicle Value': 0,
      'Vehicle Life': 0,
    },
    pinputs: {
      'Solid Assem Line': 5,
      'Liquid Assem Line': 3,
      "Pack'g Assem Line": 3,
      'Tablets_Selected': true,
      'Cream_Selected': true,
    },
    pcinputs: {
      'Tablet Production Capacity': 50,
      'Capsule Production Capacity': 30,
      'Liquid Production Capacity': 20,
      'Ointment Production Capacity': 10,
    },
    ucinputs: {
      'Electricity Usage': 1000,
      'Electricity Rate': 0.10,
      'Water Usage': 50,
      'Water Rate': 0.005,
      'Steam Usage': 10,
      'Steam Rate': 15,
      'Year 1 Days': 300,
      'Year 1 Hours': 24,
      'Year 2 Days': 320,
      'Year 2 Hours': 24,
      'Year 3-5 Days': 330,
      'Year 3-5 Hours': 24,
    },
    linputs: {
      'Production Manager':        0.150,
      'Production Operators':      0.300,
      'Process Engineer':          0.120,
      'Process Technician':        0.100,
      'QA Pharmacist':             0.180,
      'Production Pharmacist':     0.180,
      'Manufacturing Chemist':     0.160,
      'Analytical Chemist':        0.140,
      'General Manager':           0.200,
      'Sales & Marketing Manager': 0.180,
      'Accountant':                0.050,
      'Procurement Officer':       0.060,
      'Support Staff':             0.040,
      'Packers':                   0.030,
      'Secretary':                 0.025,
      'Security':                  0.020,
      'Cleaner':                   0.015,
      'Movers':                    0.010,
      'Canteen Staff':             0.018,
      'Driver':                    0.012,
    },
    unitCosts: {
      'Tablet - Production Cost': 0.03,
      'Tablet - Selling Price':   0.047,
      'Capsule - Production Cost':0.05,
      'Capsule - Selling Price':  0.08,
      'Liquid - Production Cost': 1.5,
      'Liquid - Selling Price':   2.48,
      'Ointment - Production Cost':3.0,
      'Ointment - Selling Price': 4.8,
    },
    rawMaterialRows:    [{ quantity: 500000, unitCost: 1.8 }],
    fwinputs: {
      'Tablets Freight': 0.02,
      'Capsules Freight':0.03,
      'Liquid Freight':  0.05,
      'Ointment Freight':0.04,
      'Sales Commission (%)': 7.0,
    },
    irrinputs: {
      'Initial Investment ($)':    1000000,
      'Discount Rate (%)':         0.10,
      'Cash Flow Horizon (years)': 10,
      'Revenue Growth Range (%)':  0.15,
    },
    inflationRows: [{ year: 2024, rate: 3.8 }],
    wcRows:        [{ year: 2024, arDays:45, invDays:30, prepaidDays:5, otherAssetDays:0, apDays:60, olDays:10 }],
    deRows:        [{ year: 2024, debt:0, equity:0 }],
    eqRows:        [{ year: 2024, begin:100, issued:0, ending:100, dividendRate:0, retained:0, dividendsPaid:0 }],
    debts:         [{ id: Date.now(), name:'Debt 1', amount:0.01, interestRate:0.01, duration:2 }],
    cogs: 0,
}